---
- name: Install dumb init
  get_url:
    dest: /usr/bin/dumb-init
    url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
    mode: 0775
    validate_certs: no
- name: Install python and pip
  apk:
    name: python-pip
    state: present
    update_cache: yes
- name: add testing repository to apk lists
  lineinfile:
    path: /etc/apk/repositories
    line: 'http://dl-2.alpinelinux.org/alpine/edge/community/'
    state: present
- name: Install shadow package for passwd utilities
  apk:
    name: shadow
    state: present
- name: Create flask user
  user:
    name: flask
    uid: 1000
    group: root
    state: present
    createhome: yes
    home: "/app"
- name: Copy source into container
  synchronize:
    src: "/src/"
    dest: "/app"
  remote_user: flask
- name: Install Python dependencies
  pip:
    requirements: /app/requirements.txt
  